//This source code is generated by UI Designer Studio.

#include <stdio.h>
#include <string.h>
#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "MenuCommonItemRes.c"
//#include "UIFlow.h"
#include "../../../T800x480/UIFlow.h"
#include "MenuId.h"

static UINT32 MenuCommonItemIndex;
static BOOL MenuCommonItemTPKeyHasPressed=FALSE;

static UINT32 g_uiTouchKeyTimerID       = NULL_TIMER;

//---------------------MenuCommonItemCtrl Control List---------------------------
CTRL_LIST_BEGIN(MenuCommonItem)
CTRL_LIST_ITEM(MenuCommonItem_BG)
CTRL_LIST_ITEM(MenuCommonItem_Menu)
CTRL_LIST_ITEM(MenuCommonItem_Button_Return)
CTRL_LIST_ITEM(MenuCommonItem_StaticTxt_Title)
CTRL_LIST_END

//----------------------MenuCommonItemCtrl Event---------------------------
INT32 MenuCommonItem_OnOpen(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_OnClose(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_OnChildClose(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_OnKeyMode(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_OnKeyShutter2(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_OnReverseGear(VControl *, UINT32, UINT32 *);

EVENT_BEGIN(MenuCommonItem)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,MenuCommonItem_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,MenuCommonItem_OnClose)
EVENT_ITEM(NVTEVT_CHILD_CLOSE,MenuCommonItem_OnChildClose)
EVENT_ITEM(NVTEVT_KEY_DOWN,MenuCommonItem_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_LEFT,MenuCommonItem_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_RIGHT,MenuCommonItem_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_MENU,MenuCommonItem_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE,MenuCommonItem_OnKeyMode)
//EVENT_ITEM(NVTEVT_KEY_SHUTTER2,MenuCommonItem_OnKeyShutter2)
EVENT_ITEM(NVTEVT_REVERSEGEAR,MenuCommonItem_OnReverseGear)

EVENT_END

static UINT8 g_PageNumBuf[8];

void MenuCommon_CalcPageInfo(VControl *pCtrl)
{
#if 0
    UINT32  i, uiItem, uiCurrItem, uiTotalItem, uiTotalItemOri;
    UINT32  uiItemPerPage, uiCurrPage, uiTotalPage;

    uiItem = UxMenu_GetData(pCtrl, MNU_CURITM);          // current item number in menu (include disabled items)
    uiItemPerPage = UxMenu_GetData(pCtrl, MNU_PAGEITEM); // items per page
    uiTotalItemOri = UxMenu_GetData(pCtrl, MNU_TOTITM);  // total item number

    // check total item number and current item number (skip disabled items)
    uiCurrItem = 0;
    uiTotalItem = 0;
    for (i = 0; i < uiTotalItemOri; i++)
    {
        if (UxMenu_GetItemData(pCtrl, i, MNUITM_STATUS) == STATUS_ENABLE)
        {
            uiTotalItem++;
            if (i < uiItem)
                uiCurrItem++;
        }
    }

    uiCurrPage = (uiCurrItem / uiItemPerPage) + 1;
    uiTotalPage = ((uiTotalItem % uiItemPerPage) == 0) ? (uiTotalItem / uiItemPerPage) : (uiTotalItem / uiItemPerPage + 1);

    sprintf((char *)g_PageNumBuf, "%ld/%ld", uiCurrPage, uiTotalPage);
    UxStatic_SetData(&MenuCommonItem_PageNumCtrl, STATIC_VALUE, Txt_Pointer(g_PageNumBuf));
    UxCtrl_SetShow(&MenuCommonItem_PageNumCtrl, TRUE);
    UxCtrl_SetDirty(&MenuCommonItem_PageNumCtrl, TRUE);
#endif	
}

UINT32 TP_PhaseMenuItem_Index(VControl *pCtrl,UINT32 Y)
{
	UINT32  index;
	UINT32 uiItem,uiItemPerPage,uiTotalItemOri,uiItemHigh;
	Ux_RECT Rect;

	UxCtrl_GetPos(pCtrl,&Rect);	
       uiItemPerPage = UxMenu_GetData(pCtrl, MNU_PAGEITEM); // items per page
       uiItemHigh=Rect.y2-Rect.y1;
	 index=(Y-Rect.y1)/uiItemHigh;
     //index+=(MenuCommonItemCurrentPage-1)*uiItemPerPage;
	return index;
}

void MenuCommonItem_UpdateContent(TM_MENU* pMenu)
{
    TM_PAGE*    pPage;
    TM_ITEM*    pItem; 
    TM_OPTION*  pOption;
	
    UINT32      i;
    UINT32      uiIcon[2]; // 2 pages per menu
    
    pPage = &pMenu->pPages[pMenu->SelPage];
    pMenu->Status = TMS_ON_ITEM;//TMS_ON_TAB; // current menu status is TAB
    
    UxMenu_SetData(&MenuCommonItem_MenuCtrl, MNU_TOTITM, pPage->Count);

    if (pMenu->Status == TMS_ON_TAB)
    {
        UxMenu_SetData(&MenuCommonItem_MenuCtrl, MNU_CURITM, 0); // reset current item to 0
    }

    for (i = 0; i < pPage->Count; i++)
    {
        pItem = &pPage->pItems[i];		
        UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, i, MNUITM_STRID,  pItem->TextId);
        UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, i, MNUITM_ICONID, pItem->IconId);
	  
        if(pItem->Count != 0 && pItem->SysFlag != 0)		
        {
	  	pOption = &pItem->pOptions[SysGetFlag(pItem->SysFlag)];		        
        	UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, i, MNUITM_VALUE,  pOption->TextId);	
        }
	  else
        {
        	UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, i, MNUITM_VALUE,  STRID_NULL);	
        }
    }
    for (i = 0; i < pMenu->Count; i++) 
    {
        if ((UINT32)pMenu->SelPage == i)
            uiIcon[i] = (&pMenu->pPages[i])->IconId;
        else
            uiIcon[i] = (&pMenu->pPages[i])->IconIdX;
    }
    if (pMenu->Status == TMS_ON_ITEM)
    {
        for (i = 0; i < pPage->Count; i++)
            UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, i, MNUITM_STATUS, STATUS_ENABLE); 
    }  
    UxStatic_SetData(&MenuCommonItem_StaticTxt_TitleCtrl, STATIC_VALUE, pPage->TextId);
	
     UxCtrl_SetDirty(&MenuCommonItemCtrl, TRUE);
}


INT32 MenuCommonItem_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //UINT32      i;
    TM_MENU*    pMenu = TM_GetMenu();

	pMenu->Status = TMS_ON_TAB; // current menu status is TAB
    pMenu->SelPage = 0;         // reset page to 0

    TM_MENU_CALLBACK(pMenu, TMM_ENTER_ITEM, 0);

    MenuCommonItem_UpdateContent(pMenu);
#if 0
    UxCtrl_SetShow(&MenuCommonItem_TipsIconLDRCtrl, TRUE);
    UxCtrl_SetShow(&MenuCommonItem_TipsIconLUDRCtrl, FALSE);
    UxCtrl_SetShow(&MenuCommonItem_TipsIconLUDOKCtrl, FALSE);
#endif
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 MenuCommonItem_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 MenuCommonItem_OnChildClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    TM_MENU*    pMenu = TM_GetMenu();
    UINT32      uiItem,uiOption;

    pMenu->Status = TMS_ON_ITEM;
    MenuCommonItem_UpdateContent(pMenu);
#if 0
    UxCtrl_SetShow(&MenuCommonItem_TipsIconLDRCtrl, FALSE);
    UxCtrl_SetShow(&MenuCommonItem_TipsIconLUDRCtrl, TRUE);
    UxCtrl_SetShow(&MenuCommonItem_TipsIconLUDOKCtrl, FALSE);
#endif
    Ux_DefaultEvent(pCtrl,NVTEVT_CHILD_CLOSE,paramNum,paramArray);
    if (paramNum>=2)
    {
        uiItem = paramArray[0];
        uiOption = paramArray[1];
        if (uiItem == IDM_TV_MODE)
        {
            Ux_CloseWindow(&MenuCommonItemCtrl, 0);
        }
    }
    return NVTEVT_CONSUME;
}
INT32 MenuCommonItem_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32      i;
    TM_MENU*    pMenu = TM_GetMenu();
    TM_PAGE*    pPage;

    if (pMenu->Status == TMS_ON_TAB)
    {
        pMenu->Status = TMS_ON_ITEM;
        pPage = &pMenu->pPages[pMenu->SelPage];

        for (i = 0; i < pPage->Count; i++)
            UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, i, MNUITM_STATUS, STATUS_ENABLE); // enable all items (for page info calculating)

        MenuCommon_CalcPageInfo(&MenuCommonItem_MenuCtrl); // calculate page information for display
#if 0
        UxCtrl_SetShow(&MenuCommonItem_TipsIconLDRCtrl, FALSE);
        UxCtrl_SetShow(&MenuCommonItem_TipsIconLUDRCtrl, TRUE);
        UxCtrl_SetShow(&MenuCommonItem_TipsIconLUDOKCtrl, FALSE);
#endif
        return NVTEVT_CONSUME;
    }

    return NVTEVT_PASS;
}
INT32 MenuCommonItem_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    TM_MENU*    pMenu = TM_GetMenu();

    if (pMenu->Status == TMS_ON_TAB)
    {
        TM_ShiftTab(pMenu, -1);
        MenuCommonItem_UpdateContent(pMenu);
        return NVTEVT_CONSUME;
    }

    return NVTEVT_PASS;
}
INT32 MenuCommonItem_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    TM_MENU*    pMenu = TM_GetMenu();

    if (pMenu->Status == TMS_ON_TAB)
    {
        TM_ShiftTab(pMenu, +1);
        MenuCommonItem_UpdateContent(pMenu);
        return NVTEVT_CONSUME;
    }

    return NVTEVT_PASS;
}
INT32 MenuCommonItem_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
 TM_PAGE*    pPage;
 TM_MENU*    pMenu = TM_GetMenu();

    pPage = &pMenu->pPages[pMenu->SelPage];

    if (pPage->TextId == STRID_SETUP)
        Ux_CloseWindow(pCtrl,0);
    else {
        if (pMenu->Status == TMS_ON_TAB)
        {
            TM_ShiftTab(pMenu, +1);
            MenuCommonItem_UpdateContent(pMenu);
        } else {
            Ux_CloseWindow(pCtrl,0);
        }
    }
    return NVTEVT_CONSUME;
}
INT32 MenuCommonItem_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(&UISetupObjCtrl,NVTEVT_EXE_CHANGEDSCMODE,1,DSCMODE_CHGTO_NEXT);
    return NVTEVT_CONSUME;
}
INT32 MenuCommonItem_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(&UISetupObjCtrl,NVTEVT_FORCETO_LIVEVIEW_MODE,0);
    return NVTEVT_CONSUME;
}
INT32 MenuCommonItem_OnReverseGear(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_CloseWindow(pCtrl,0);
    return NVTEVT_CONSUME;
}
//---------------------MenuCommonItem_BGCtrl Control List---------------------------
CTRL_LIST_BEGIN(MenuCommonItem_BG)
CTRL_LIST_END

//----------------------MenuCommonItem_BGCtrl Event---------------------------
EVENT_BEGIN(MenuCommonItem_BG)
EVENT_END

//----------------------MenuCommonItem_MenuCtrl Event---------------------------
INT32 MenuCommonItem_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_Menu_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_Menu_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_Menu_OnTouchPanelKey(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_Menu_OnTimer(VControl *, UINT32, UINT32 *);

EVENT_BEGIN(MenuCommonItem_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,MenuCommonItem_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,MenuCommonItem_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_LEFT,MenuCommonItem_Menu_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_RIGHT,MenuCommonItem_Menu_OnKeyRight)
//EVENT_ITEM(NVTEVT_KEY_ENTER,MenuCommonItem_Menu_OnKeyEnter)
#if((_MODEL_DSC_ == _MODEL_CARDV_B50_)||(_MODEL_DSC_== _MODEL_DUAL_NAZHIDA_))
EVENT_ITEM(NVTEVT_KEY_CUSTOM1,MenuCommonItem_Menu_OnKeyEnter)
#else
EVENT_ITEM(NVTEVT_KEY_SHUTTER2,MenuCommonItem_Menu_OnKeyEnter)
#endif
EVENT_ITEM(NVTEVT_TOUCHPANEL_KEY,MenuCommonItem_Menu_OnTouchPanelKey)
EVENT_ITEM(NVTEVT_TIMER,MenuCommonItem_Menu_OnTimer)


EVENT_END

INT32 MenuCommonItem_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    TM_MENU*    pMenu = TM_GetMenu();

    if (pMenu->Status == TMS_ON_ITEM)
    {
        Ux_SendEvent(pCtrl, NVTEVT_PREVIOUS_ITEM, 0);       // go to previous item firstly
        MenuCommon_CalcPageInfo(&MenuCommonItem_MenuCtrl);  // calculate page information for display
    }

    return NVTEVT_CONSUME;
}
INT32 MenuCommonItem_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    TM_MENU*    pMenu = TM_GetMenu();

    if (pMenu->Status == TMS_ON_ITEM)
    {
        Ux_SendEvent(pCtrl, NVTEVT_NEXT_ITEM, 0);           // go to next item firstly
        MenuCommon_CalcPageInfo(&MenuCommonItem_MenuCtrl);  // calculate page information for display
    }

    return NVTEVT_CONSUME;
}
INT32 MenuCommonItem_Menu_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32      i;
    TM_MENU*    pMenu = TM_GetMenu();
    TM_PAGE*    pPage;

    if (pMenu->Status == TMS_ON_ITEM)
    {
        pMenu->Status = TMS_ON_TAB;
        pPage = &pMenu->pPages[pMenu->SelPage];

        UxMenu_SetData(pCtrl, MNU_CURITM, 0);               // return to 1st item
        MenuCommon_CalcPageInfo(&MenuCommonItem_MenuCtrl);  // calculate page information for display

        for (i = 0; i < pPage->Count; i++)
        {
            UxMenu_SetItemData(pCtrl, i, MNUITM_STATUS, (STATUS_DISABLE | STATUS_NORMAL_BIT)); // disable all items
        }
#if 0
        UxCtrl_SetShow(&MenuCommonItem_TipsIconLDRCtrl, TRUE);
        UxCtrl_SetShow(&MenuCommonItem_TipsIconLUDRCtrl, FALSE);
        UxCtrl_SetShow(&MenuCommonItem_TipsIconLUDOKCtrl, FALSE);
#endif		
    }

    return NVTEVT_CONSUME;
}
INT32 MenuCommonItem_Menu_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    TM_MENU*    pMenu = TM_GetMenu();
    TM_PAGE*    pPage;
    TM_ITEM*    pItem;

    if (pMenu->Status == TMS_ON_ITEM)
    {
        pPage = &pMenu->pPages[pMenu->SelPage];
        pPage->SelItem = UxMenu_GetData(&MenuCommonItem_MenuCtrl, MNU_CURITM); // update selected item of tab menu
        pItem = &pPage->pItems[pPage->SelItem];

        if (pItem->Count != 0 && pItem->SysFlag != 0)   // standard process
        {
            if (TM_MENU_CALLBACK(pMenu, TMM_ENTER_OPTION, MAKE_LONG(pItem->ItemId, 0)) == TMF_PASS_MESSAGE)
            {
                return NVTEVT_CONSUME;
            }
        }
#if 0
        UxStatic_SetData(&MenuCommonItem_TitleTextCtrl, STATIC_VALUE, pItem->TextId);		
        UxCtrl_SetShow(&MenuCommonItem_TipsIconLDRCtrl, FALSE);
        UxCtrl_SetShow(&MenuCommonItem_TipsIconLUDRCtrl, FALSE);
        UxCtrl_SetShow(&MenuCommonItem_TipsIconLUDOKCtrl, TRUE);
        UxCtrl_SetShow(&MenuCommonItem_PageNumCtrl, FALSE);
#endif
        UxStatic_SetData(&MenuCommonItem_StaticTxt_TitleCtrl, STATIC_VALUE, pItem->TextId);
        Ux_Redraw();

        if (pItem->Count != 0 && pItem->SysFlag != 0)   // standard process
        {
            pMenu->Status = TMS_ON_OPTION;
            Ux_OpenWindow(&MenuCommonOptionCtrl, 0);
        }
        else if (pItem->pOptions != 0)                  // custom process
        {
            pMenu->Status = TMS_ON_CUSTOM;
            TM_ITEM_CALLBACK(pItem, 0, 0);              // execute custom menu flow
        }
    }

    return NVTEVT_CONSUME;
}

INT32 MenuCommonItem_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return MenuCommonItem_Menu_OnKeyRight(pCtrl, paramNum, paramArray);
}

INT32 MenuCommonItem_Menu_OnTouchPanelKey(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32 P1,P2;
    UINT32  uiSoundMask,uiSelect;
  
    if(paramNum>0)
	P1= paramArray[0];
    if(paramNum>1)	
	P2=paramArray[1];  
  
	TM_PAGE*    pPage;
	TM_MENU*    pMenu = TM_GetMenu();
	pPage = &pMenu->pPages[pMenu->SelPage];
		 
      if(TPIsOnRange(&MenuCommonItem_Button_ReturnCtrl,P1,P2)==TRUE)
    	{
     	      Ux_CloseWindow(&MenuCommonItemCtrl,0);			   
    	}						
	else if(TPIsOnRangeMenu(&MenuCommonItem_MenuCtrl,P1,P2)==TRUE)
	{
	       MenuCommonItemTPKeyHasPressed=TRUE;
 		MenuCommonItemIndex = TP_PhaseMenuItem_Index(&MenuCommonItem_MenuCtrl,P2);		
		if((MenuCommonItemIndex>=0)&&(MenuCommonItemIndex<7))
		{
		  UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, MenuCommonItemIndex, MNUITM_STATUS, (STATUS_DISABLE| STATUS_FOCUS_BIT));
                if (g_uiTouchKeyTimerID == NULL_TIMER)
                {
                    g_uiTouchKeyTimerID = GxTimer_StartTimer(100, NVTEVT_01SEC_TIMER, ONE_SHOT);
                }		
		}
		else
		{
			MenuCommonItemIndex=0;
		}
	}
	return NVTEVT_CONSUME;
}

INT32 MenuCommonItem_Menu_OnTimer(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    NVTEVT event;
    TM_MENU*    pMenu = TM_GetMenu();


    if(paramNum > 0)
    {
       event = paramArray[0];
    } else {
       return NVTEVT_CONSUME;
    }
    switch(event)
    {
        case NVTEVT_01SEC_TIMER: 
	     if(MenuCommonItemTPKeyHasPressed==TRUE)
	     {
      	            MenuCommonItemTPKeyHasPressed=FALSE;
	            if (g_uiTouchKeyTimerID != NULL_TIMER)
	            {
	                g_uiTouchKeyTimerID=NULL_TIMER;
	                GxTimer_StopTimer(&g_uiTouchKeyTimerID);
	            }			
	    	     //MenuCommonItem_UpdateContent(pMenu);	
			UxMenu_SetData(&MenuCommonItem_MenuCtrl, MNU_CURITM, MenuCommonItemIndex);               // return to 1st item								
			return MenuCommonItem_Menu_OnKeyRight(pCtrl, paramNum, paramArray);		    	     
	     }
        break;
    }
    return NVTEVT_CONSUME;
}

//----------------------MenuCommonItem_Button_ReturnCtrl Event---------------------------
EVENT_BEGIN(MenuCommonItem_Button_Return)
EVENT_END

//----------------------MenuCommonItem_StaticTxt_TitleCtrl Event---------------------------
EVENT_BEGIN(MenuCommonItem_StaticTxt_Title)
EVENT_END

