//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIFlowWndWaitMomentRes.c"
#include "UIFlowWndWaitMoment.h"
#include "PrjCfg.h"

//---------------------UIFlowWndWaitMomentCtrl Debug Definition -----------------------------
#define _UIFLOWWNDWAITMOMENT_ERROR_MSG        1
#define _UIFLOWWNDWAITMOMENT_TRACE_MSG        0

#if (_UIFLOWWNDWAITMOMENT_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIFlowWndWaitMomentErrMsg(...)            debug_msg ("^R UIFlowWndWaitMoment: "__VA_ARGS__)
#else
#define UIFlowWndWaitMomentErrMsg(...)
#endif

#if (_UIFLOWWNDWAITMOMENT_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIFlowWndWaitMomentTraceMsg(...)          debug_msg ("^B UIFlowWndWaitMoment: "__VA_ARGS__)
#else
#define UIFlowWndWaitMomentTraceMsg(...)
#endif

//---------------------UIFlowWndWaitMomentCtrl Global Variables -----------------------------

//---------------------UIFlowWndWaitMomentCtrl Prototype Declaration  -----------------------

//---------------------UIFlowWndWaitMomentCtrl Public API  ----------------------------------

//---------------------UIFlowWndWaitMomentCtrl Private API  ---------------------------------
//---------------------UIFlowWndWaitMomentCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndWaitMoment)
CTRL_LIST_ITEM(UIFlowWndWaitMoment_StatusTXT_Msg)
CTRL_LIST_END

//----------------------UIFlowWndWaitMomentCtrl Event---------------------------
INT32 UIFlowWndWaitMoment_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndWaitMoment_OnClose(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWndWaitMoment)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIFlowWndWaitMoment_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIFlowWndWaitMoment_OnClose)
EVENT_END

INT32 UIFlowWndWaitMoment_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndWaitMoment_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
//----------------------UIFlowWndWaitMoment_StatusTXT_MsgCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndWaitMoment_StatusTXT_Msg)
EVENT_END

