//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIFlowWndUSBRes.c"
#include "UIFlowWndUSB.h"
#include "PrjCfg.h"

//---------------------UIFlowWndUSBCtrl Debug Definition -----------------------------
#define _UIFLOWWNDUSB_ERROR_MSG        1
#define _UIFLOWWNDUSB_TRACE_MSG        0

#if (_UIFLOWWNDUSB_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIFlowWndUSBErrMsg(...)            debug_msg ("^R UIFlowWndUSB: "__VA_ARGS__)
#else
#define UIFlowWndUSBErrMsg(...)
#endif

#if (_UIFLOWWNDUSB_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIFlowWndUSBTraceMsg(...)          debug_msg ("^B UIFlowWndUSB: "__VA_ARGS__)
#else
#define UIFlowWndUSBTraceMsg(...)
#endif

//---------------------UIFlowWndUSBCtrl Global Variables -----------------------------

//---------------------UIFlowWndUSBCtrl Prototype Declaration  -----------------------

//---------------------UIFlowWndUSBCtrl Public API  ----------------------------------

//---------------------UIFlowWndUSBCtrl Private API  ---------------------------------
//---------------------UIFlowWndUSBCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndUSB)
CTRL_LIST_ITEM(UIFlowWndMSDC_StaticTxt_MassStorage)
CTRL_LIST_END

//----------------------UIFlowWndUSBCtrl Event---------------------------
INT32 UIFlowWndUSB_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndUSB_OnClose(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWndUSB)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIFlowWndUSB_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIFlowWndUSB_OnClose)
EVENT_END

INT32 UIFlowWndUSB_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndUSB_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
//----------------------UIFlowWndMSDC_StaticTxt_MassStorageCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMSDC_StaticTxt_MassStorage)
EVENT_END

