//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDSETUPCARNUMBER_H
#define UIMENUWNDSETUPCARNUMBER_H

#include "UIFramework.h"

extern VControl UIMenuWndSetupCarNumberCtrl;//Panel type 

extern VControl UIMenuWndSetupCarNumber_TabCtrl;//Tab type 

typedef enum
{
UIMenuWndSetupCarNumber_Tab_UIMenuWndSetupCarNumber_Button1,
UIMenuWndSetupCarNumber_Tab_UIMenuWndSetupCarNumber_Button2,
UIMenuWndSetupCarNumber_Tab_UIMenuWndSetupCarNumber_Button3,
UIMenuWndSetupCarNumber_Tab_UIMenuWndSetupCarNumber_Button4,
UIMenuWndSetupCarNumber_Tab_UIMenuWndSetupCarNumber_Button5,
UIMenuWndSetupCarNumber_Tab_UIMenuWndSetupCarNumber_Button6,
UIMenuWndSetupCarNumber_Tab_UIMenuWndSetupCarNumber_Button7,
UIMenuWndSetupCarNumber_Tab_MAX
}UIMenuWndSetupCarNumber_Tab_Setting;

extern VControl UIMenuWndSetupCarNumber_Button1Ctrl;//Button type 

extern VControl UIMenuWndSetupCarNumber_Button2Ctrl;//Button type 

extern VControl UIMenuWndSetupCarNumber_Button3Ctrl;//Button type 

extern VControl UIMenuWndSetupCarNumber_Button4Ctrl;//Button type 

extern VControl UIMenuWndSetupCarNumber_Button5Ctrl;//Button type 

extern VControl UIMenuWndSetupCarNumber_Button6Ctrl;//Button type 

extern VControl UIMenuWndSetupCarNumber_Button7Ctrl;//Button type 

//---------------------UIMenuWndSetupCarNumberCtrl User Export---------------------------
#endif
