//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDEDOG_H
#define UIFLOWWNDEDOG_H

#include "UIFramework.h"

extern VControl UIFlowwndEdogCtrl;//Panel type 

//---------------------UIFlowwndEdogCtrl User Export---------------------------
#endif
