//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDEDOGRES_H
#define UIFLOWWNDEDOGRES_H

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIDisplayUtil.h"
//------------------------------------------------------------

SHOW_MAP_BEGIN(Skin1)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin1,0,0,799,479)

SHOW_MAP_BEGIN(UIFlowwndEdog)
SHOW_MAP_BODY(Skin1)
SHOW_MAP_END

DECLARE_EVENT(UIFlowwndEdog)
DECLARE_CTRL_LIST(UIFlowwndEdog)
CREATE_CTRL(UIFlowwndEdog,UIFlowwndEdog,CTRL_WND,NULL,0 ,0,0,799,479)
#endif
