//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIFlowwndEdogRes.c"
#include "UIFlowwndEdog.h"
#include "PrjCfg.h"

//---------------------UIFlowwndEdogCtrl Debug Definition -----------------------------
#define _UIFLOWWNDEDOG_ERROR_MSG        1
#define _UIFLOWWNDEDOG_TRACE_MSG        0

#if (_UIFLOWWNDEDOG_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIFlowwndEdogErrMsg(...)            debug_msg ("^R UIFlowwndEdog: "__VA_ARGS__)
#else
#define UIFlowwndEdogErrMsg(...)
#endif

#if (_UIFLOWWNDEDOG_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIFlowwndEdogTraceMsg(...)          debug_msg ("^B UIFlowwndEdog: "__VA_ARGS__)
#else
#define UIFlowwndEdogTraceMsg(...)
#endif

//---------------------UIFlowwndEdogCtrl Global Variables -----------------------------

//---------------------UIFlowwndEdogCtrl Prototype Declaration  -----------------------

//---------------------UIFlowwndEdogCtrl Public API  ----------------------------------

//---------------------UIFlowwndEdogCtrl Private API  ---------------------------------
//---------------------UIFlowwndEdogCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowwndEdog)
CTRL_LIST_END

//----------------------UIFlowwndEdogCtrl Event---------------------------
INT32 UIFlowwndEdog_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIFlowwndEdog_OnClose(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowwndEdog)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIFlowwndEdog_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIFlowwndEdog_OnClose)
EVENT_END

INT32 UIFlowwndEdog_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowwndEdog_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
