//This source code is generated by UI Designer Studio.

#ifndef MENUCOMMONITEM_H
#define MENUCOMMONITEM_H

#include "UIFramework.h"

extern VControl MenuCommonItemCtrl;//Panel type 

extern VControl MenuCommonItem_BGCtrl;//Panel type 

extern VControl MenuCommonItem_MenuCtrl;//Menu type 

typedef enum
{
MenuCommonItem_Menu_STRID_12M,
MenuCommonItem_Menu_STRID_10M,
MenuCommonItem_Menu_STRID_9M,
MenuCommonItem_Menu_STRID_8M,
MenuCommonItem_Menu_STRID_7M,
MenuCommonItem_Menu_STRID_6M,
MenuCommonItem_Menu_STRID_5M,
MenuCommonItem_Menu_STRID_4M,
MenuCommonItem_Menu_MAX
}MenuCommonItem_Menu_Setting;

extern VControl MenuCommonItem_Button_ReturnCtrl;//Static type 

extern VControl MenuCommonItem_StaticTxt_TitleCtrl;//Static type 

//---------------------MenuCommonItemCtrl User Export---------------------------
#endif
