//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "MenuCommonOptionRes.c"
#include "MenuCommonOption.h"
#include "PrjCfg.h"

//---------------------MenuCommonOptionCtrl Debug Definition -----------------------------
#define _MENUCOMMONOPTION_ERROR_MSG        1
#define _MENUCOMMONOPTION_TRACE_MSG        0

#if (_MENUCOMMONOPTION_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define MenuCommonOptionErrMsg(...)            debug_msg ("^R MenuCommonOption: "__VA_ARGS__)
#else
#define MenuCommonOptionErrMsg(...)
#endif

#if (_MENUCOMMONOPTION_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define MenuCommonOptionTraceMsg(...)          debug_msg ("^B MenuCommonOption: "__VA_ARGS__)
#else
#define MenuCommonOptionTraceMsg(...)
#endif

//---------------------MenuCommonOptionCtrl Global Variables -----------------------------

//---------------------MenuCommonOptionCtrl Prototype Declaration  -----------------------

//---------------------MenuCommonOptionCtrl Public API  ----------------------------------

//---------------------MenuCommonOptionCtrl Private API  ---------------------------------
//---------------------MenuCommonOptionCtrl Control List---------------------------
CTRL_LIST_BEGIN(MenuCommonOption)
CTRL_LIST_ITEM(MenuCommonOption_Panel)
CTRL_LIST_ITEM(MenuCommonOption_Button_Return)
CTRL_LIST_ITEM(MenuCommonOption_Menu)
CTRL_LIST_END

//----------------------MenuCommonOptionCtrl Event---------------------------
INT32 MenuCommonOption_OnOpen(VControl *, UINT32, UINT32 *);
INT32 MenuCommonOption_OnClose(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(MenuCommonOption)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,MenuCommonOption_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,MenuCommonOption_OnClose)
EVENT_END

INT32 MenuCommonOption_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 MenuCommonOption_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
//---------------------MenuCommonOption_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(MenuCommonOption_Panel)
CTRL_LIST_END

//----------------------MenuCommonOption_PanelCtrl Event---------------------------
EVENT_BEGIN(MenuCommonOption_Panel)
EVENT_END

//----------------------MenuCommonOption_Button_ReturnCtrl Event---------------------------
EVENT_BEGIN(MenuCommonOption_Button_Return)
EVENT_END

//----------------------MenuCommonOption_MenuCtrl Event---------------------------
INT32 MenuCommonOption_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 MenuCommonOption_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 MenuCommonOption_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(MenuCommonOption_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,MenuCommonOption_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,MenuCommonOption_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,MenuCommonOption_Menu_OnKeyEnter)
EVENT_END

INT32 MenuCommonOption_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 MenuCommonOption_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 MenuCommonOption_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
