//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "MenuCommonItemRes.c"
#include "MenuCommonItem.h"
#include "PrjCfg.h"

//---------------------MenuCommonItemCtrl Debug Definition -----------------------------
#define _MENUCOMMONITEM_ERROR_MSG        1
#define _MENUCOMMONITEM_TRACE_MSG        0

#if (_MENUCOMMONITEM_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define MenuCommonItemErrMsg(...)            debug_msg ("^R MenuCommonItem: "__VA_ARGS__)
#else
#define MenuCommonItemErrMsg(...)
#endif

#if (_MENUCOMMONITEM_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define MenuCommonItemTraceMsg(...)          debug_msg ("^B MenuCommonItem: "__VA_ARGS__)
#else
#define MenuCommonItemTraceMsg(...)
#endif

//---------------------MenuCommonItemCtrl Global Variables -----------------------------

//---------------------MenuCommonItemCtrl Prototype Declaration  -----------------------

//---------------------MenuCommonItemCtrl Public API  ----------------------------------

//---------------------MenuCommonItemCtrl Private API  ---------------------------------
//---------------------MenuCommonItemCtrl Control List---------------------------
CTRL_LIST_BEGIN(MenuCommonItem)
CTRL_LIST_ITEM(MenuCommonItem_BG)
CTRL_LIST_ITEM(MenuCommonItem_Menu)
CTRL_LIST_ITEM(MenuCommonItem_Button_Return)
CTRL_LIST_ITEM(MenuCommonItem_StaticTxt_Title)
CTRL_LIST_END

//----------------------MenuCommonItemCtrl Event---------------------------
INT32 MenuCommonItem_OnOpen(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_OnClose(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(MenuCommonItem)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,MenuCommonItem_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,MenuCommonItem_OnClose)
EVENT_END

INT32 MenuCommonItem_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 MenuCommonItem_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
//---------------------MenuCommonItem_BGCtrl Control List---------------------------
CTRL_LIST_BEGIN(MenuCommonItem_BG)
CTRL_LIST_END

//----------------------MenuCommonItem_BGCtrl Event---------------------------
EVENT_BEGIN(MenuCommonItem_BG)
EVENT_END

//----------------------MenuCommonItem_MenuCtrl Event---------------------------
EVENT_BEGIN(MenuCommonItem_Menu)
EVENT_END

//----------------------MenuCommonItem_Button_ReturnCtrl Event---------------------------
EVENT_BEGIN(MenuCommonItem_Button_Return)
EVENT_END

//----------------------MenuCommonItem_StaticTxt_TitleCtrl Event---------------------------
EVENT_BEGIN(MenuCommonItem_StaticTxt_Title)
EVENT_END

