//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndSetupDefaultSettingRes.c"
#include "UIMenuWndSetupDefaultSetting.h"
#include "PrjCfg.h"

//---------------------UIMenuWndSetupDefaultSettingCtrl Debug Definition -----------------------------
#define _UIMENUWNDSETUPDEFAULTSETTING_ERROR_MSG        1
#define _UIMENUWNDSETUPDEFAULTSETTING_TRACE_MSG        0

#if (_UIMENUWNDSETUPDEFAULTSETTING_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndSetupDefaultSettingErrMsg(...)            debug_msg ("^R UIMenuWndSetupDefaultSetting: "__VA_ARGS__)
#else
#define UIMenuWndSetupDefaultSettingErrMsg(...)
#endif

#if (_UIMENUWNDSETUPDEFAULTSETTING_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndSetupDefaultSettingTraceMsg(...)          debug_msg ("^B UIMenuWndSetupDefaultSetting: "__VA_ARGS__)
#else
#define UIMenuWndSetupDefaultSettingTraceMsg(...)
#endif

//---------------------UIMenuWndSetupDefaultSettingCtrl Global Variables -----------------------------

//---------------------UIMenuWndSetupDefaultSettingCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndSetupDefaultSettingCtrl Public API  ----------------------------------

//---------------------UIMenuWndSetupDefaultSettingCtrl Private API  ---------------------------------
//---------------------UIMenuWndSetupDefaultSettingCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupDefaultSetting)
CTRL_LIST_ITEM(UIMenuWndSetupDefaultSetting_List_Text)
CTRL_LIST_ITEM(UIMenuWndSetupDefaultSetting_Static_Text)
CTRL_LIST_END

//----------------------UIMenuWndSetupDefaultSettingCtrl Event---------------------------
INT32 UIMenuWndSetupDefaultSetting_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupDefaultSetting_OnClose(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupDefaultSetting)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndSetupDefaultSetting_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndSetupDefaultSetting_OnClose)
EVENT_END

INT32 UIMenuWndSetupDefaultSetting_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupDefaultSetting_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndSetupDefaultSetting_List_TextCtrl Event---------------------------
INT32 UIMenuWndSetupDefaultSetting_List_Text_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupDefaultSetting_List_Text_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupDefaultSetting_List_Text_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupDefaultSetting_List_Text)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndSetupDefaultSetting_List_Text_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndSetupDefaultSetting_List_Text_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndSetupDefaultSetting_List_Text_OnKeyEnter)
EVENT_END

INT32 UIMenuWndSetupDefaultSetting_List_Text_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupDefaultSetting_List_Text_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupDefaultSetting_List_Text_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndSetupDefaultSetting_Static_TextCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupDefaultSetting_Static_Text)
EVENT_END

