//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndSetupCommonCarNumberRes.c"
#include "UIMenuWndSetupCommonCarNumber.h"
#include "PrjCfg.h"

//---------------------UIMenuWndSetupCommonCarNumberCtrl Debug Definition -----------------------------
#define _UIMENUWNDSETUPCOMMONCARNUMBER_ERROR_MSG        1
#define _UIMENUWNDSETUPCOMMONCARNUMBER_TRACE_MSG        0

#if (_UIMENUWNDSETUPCOMMONCARNUMBER_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndSetupCommonCarNumberErrMsg(...)            debug_msg ("^R UIMenuWndSetupCommonCarNumber: "__VA_ARGS__)
#else
#define UIMenuWndSetupCommonCarNumberErrMsg(...)
#endif

#if (_UIMENUWNDSETUPCOMMONCARNUMBER_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndSetupCommonCarNumberTraceMsg(...)          debug_msg ("^B UIMenuWndSetupCommonCarNumber: "__VA_ARGS__)
#else
#define UIMenuWndSetupCommonCarNumberTraceMsg(...)
#endif

//---------------------UIMenuWndSetupCommonCarNumberCtrl Global Variables -----------------------------

//---------------------UIMenuWndSetupCommonCarNumberCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndSetupCommonCarNumberCtrl Public API  ----------------------------------

//---------------------UIMenuWndSetupCommonCarNumberCtrl Private API  ---------------------------------
//---------------------UIMenuWndSetupCommonCarNumberCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupCommonCarNumber)
CTRL_LIST_ITEM(UIMenuWndSetupCommonCarNumber_Tab)
CTRL_LIST_END

//----------------------UIMenuWndSetupCommonCarNumberCtrl Event---------------------------
INT32 UIMenuWndSetupCommonCarNumber_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupCommonCarNumber_OnClose(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupCommonCarNumber)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndSetupCommonCarNumber_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndSetupCommonCarNumber_OnClose)
EVENT_END

INT32 UIMenuWndSetupCommonCarNumber_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupCommonCarNumber_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndSetupCommonCarNumber_TabCtrl Event---------------------------
INT32 UIMenuWndSetupCommonCarNumber_Tab_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupCommonCarNumber_Tab_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupCommonCarNumber_Tab_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupCommonCarNumber_Tab_OnKeyRight(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupCommonCarNumber_Tab)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndSetupCommonCarNumber_Tab_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndSetupCommonCarNumber_Tab_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndSetupCommonCarNumber_Tab_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_RIGHT,UIMenuWndSetupCommonCarNumber_Tab_OnKeyRight)
EVENT_END

INT32 UIMenuWndSetupCommonCarNumber_Tab_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupCommonCarNumber_Tab_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupCommonCarNumber_Tab_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupCommonCarNumber_Tab_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndSetupCommonCarNumber_Button1Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupCommonCarNumber_Button1)
EVENT_END

//----------------------UIMenuWndSetupCommonCarNumber_Button2Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupCommonCarNumber_Button2)
EVENT_END

//----------------------UIMenuWndSetupCommonCarNumber_Button3Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupCommonCarNumber_Button3)
EVENT_END

//----------------------UIMenuWndSetupCommonCarNumber_Button4Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupCommonCarNumber_Button4)
EVENT_END

//----------------------UIMenuWndSetupCommonCarNumber_Button5Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupCommonCarNumber_Button5)
EVENT_END

//----------------------UIMenuWndSetupCommonCarNumber_Button6Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupCommonCarNumber_Button6)
EVENT_END

