//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndSetupFormatConfirmRes.c"
#include "UIMenuWndSetupFormatConfirm.h"
#include "PrjCfg.h"

//---------------------UIMenuWndSetupFormatConfirmCtrl Debug Definition -----------------------------
#define _UIMENUWNDSETUPFORMATCONFIRM_ERROR_MSG        1
#define _UIMENUWNDSETUPFORMATCONFIRM_TRACE_MSG        0

#if (_UIMENUWNDSETUPFORMATCONFIRM_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndSetupFormatConfirmErrMsg(...)            debug_msg ("^R UIMenuWndSetupFormatConfirm: "__VA_ARGS__)
#else
#define UIMenuWndSetupFormatConfirmErrMsg(...)
#endif

#if (_UIMENUWNDSETUPFORMATCONFIRM_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndSetupFormatConfirmTraceMsg(...)          debug_msg ("^B UIMenuWndSetupFormatConfirm: "__VA_ARGS__)
#else
#define UIMenuWndSetupFormatConfirmTraceMsg(...)
#endif

//---------------------UIMenuWndSetupFormatConfirmCtrl Global Variables -----------------------------

//---------------------UIMenuWndSetupFormatConfirmCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndSetupFormatConfirmCtrl Public API  ----------------------------------

//---------------------UIMenuWndSetupFormatConfirmCtrl Private API  ---------------------------------
//---------------------UIMenuWndSetupFormatConfirmCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupFormatConfirm)
CTRL_LIST_ITEM(UIMenuWndSetupFormatConfirm_List_Text)
CTRL_LIST_ITEM(UIMenuWndSetupFormatConfirm_Static_Text)
CTRL_LIST_END

//----------------------UIMenuWndSetupFormatConfirmCtrl Event---------------------------
INT32 UIMenuWndSetupFormatConfirm_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupFormatConfirm_OnClose(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupFormatConfirm)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndSetupFormatConfirm_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndSetupFormatConfirm_OnClose)
EVENT_END

INT32 UIMenuWndSetupFormatConfirm_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupFormatConfirm_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndSetupFormatConfirm_List_TextCtrl Event---------------------------
INT32 UIMenuWndSetupFormatConfirm_List_Text_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupFormatConfirm_List_Text_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupFormatConfirm_List_Text_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupFormatConfirm_List_Text)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndSetupFormatConfirm_List_Text_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndSetupFormatConfirm_List_Text_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndSetupFormatConfirm_List_Text_OnKeyEnter)
EVENT_END

INT32 UIMenuWndSetupFormatConfirm_List_Text_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupFormatConfirm_List_Text_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupFormatConfirm_List_Text_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndSetupFormatConfirm_Static_TextCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupFormatConfirm_Static_Text)
EVENT_END

