//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDPROCESSING_H
#define UIFLOWWNDPROCESSING_H

#include "UIFramework.h"

extern VControl UIFlowWndProcessingCtrl;//Panel type 

extern VControl UIFlowWndProcessing_StaticText_MsgCtrl;//Static type 

extern VControl UIFlowWndProcessing_StaticText_ProgressCtrl;//Static type 

//---------------------UIFlowWndProcessingCtrl User Export---------------------------
#endif
