//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndPlayConfirmDelRes.c"
#include "UIMenuWndPlayConfirmDel.h"
#include "PrjCfg.h"

//---------------------UIMenuWndPlayConfirmDelCtrl Debug Definition -----------------------------
#define _UIMENUWNDPLAYCONFIRMDEL_ERROR_MSG        1
#define _UIMENUWNDPLAYCONFIRMDEL_TRACE_MSG        0

#if (_UIMENUWNDPLAYCONFIRMDEL_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndPlayConfirmDelErrMsg(...)            debug_msg ("^R UIMenuWndPlayConfirmDel: "__VA_ARGS__)
#else
#define UIMenuWndPlayConfirmDelErrMsg(...)
#endif

#if (_UIMENUWNDPLAYCONFIRMDEL_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndPlayConfirmDelTraceMsg(...)          debug_msg ("^B UIMenuWndPlayConfirmDel: "__VA_ARGS__)
#else
#define UIMenuWndPlayConfirmDelTraceMsg(...)
#endif

//---------------------UIMenuWndPlayConfirmDelCtrl Global Variables -----------------------------

//---------------------UIMenuWndPlayConfirmDelCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndPlayConfirmDelCtrl Public API  ----------------------------------

//---------------------UIMenuWndPlayConfirmDelCtrl Private API  ---------------------------------
//---------------------UIMenuWndPlayConfirmDelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPlayConfirmDel)
CTRL_LIST_ITEM(UIMenuWndPlayConfirmDel_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPlayConfirmDelCtrl Event---------------------------
INT32 UIMenuWndPlayConfirmDel_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayConfirmDel_OnClose(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPlayConfirmDel)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndPlayConfirmDel_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndPlayConfirmDel_OnClose)
EVENT_END

INT32 UIMenuWndPlayConfirmDel_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayConfirmDel_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
//---------------------UIMenuWndPlayConfirmDel_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPlayConfirmDel_Panel)
CTRL_LIST_ITEM(UIMenuWndPlayConfirmDel_Menu)
CTRL_LIST_ITEM(UIMenuWndPlayConfirmDel_StatusText)
CTRL_LIST_END

//----------------------UIMenuWndPlayConfirmDel_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPlayConfirmDel_Panel)
EVENT_END

//----------------------UIMenuWndPlayConfirmDel_MenuCtrl Event---------------------------
INT32 UIMenuWndPlayConfirmDel_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayConfirmDel_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayConfirmDel_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPlayConfirmDel_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndPlayConfirmDel_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndPlayConfirmDel_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndPlayConfirmDel_Menu_OnKeyEnter)
EVENT_END

INT32 UIMenuWndPlayConfirmDel_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayConfirmDel_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayConfirmDel_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndPlayConfirmDel_StatusTextCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPlayConfirmDel_StatusText)
EVENT_END

