//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDPROCESSINGRES_H
#define UIFLOWWNDPROCESSINGRES_H

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIDisplayUtil.h"
//------------------------------------------------------------

SHOW_MAP_BEGIN(Skin1)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin1,0,0,319,239)

SHOW_ITEM_RECT(CMD_Rectangle,Rect5,0,0,219,139,16,2,0,14,0,0,0)
SHOW_MAP_BEGIN(Skin3)
SHOW_MAP_BODY(Rect5)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin3,0,0,219,139)

SHOW_ITEM_TEXT(CMD_Text|CMD_ITEM,Text7,0,10,219,69,STRID_NULL,0,0,0,0,2,1,1,0,0,17,0,0,0,0)
SHOW_MAP_BEGIN(Normal2)
SHOW_MAP_BODY(Skin3)
SHOW_MAP_BODY(Text7)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Normal2,50,50,269,189)

SHOW_MAP_BEGIN(UIFlowWndProcessing_StaticText_Msg)
SHOW_MAP_BODY(Normal2)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndProcessing_StaticText_Msg)
CREATE_STATIC_DATA(UIFlowWndProcessing_StaticText_Msg,STRID_PROCESSING)
CREATE_STATIC_CTRL(UIFlowWndProcessing_StaticText_Msg,0,50,50,269,189)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_ITEM_RECT(CMD_Rectangle,Rect12,0,0,59,29,16,2,0,14,0,0,0)
SHOW_MAP_BEGIN(Skin10)
SHOW_MAP_BODY(Rect12)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin10,0,0,59,29)

SHOW_ITEM_TEXT(CMD_Text|CMD_ITEM,Text14,0,0,59,29,STRID_NULL,0,0,0,0,2,1,1,0,0,18,0,0,0,0)
SHOW_MAP_BEGIN(Normal9)
SHOW_MAP_BODY(Skin10)
SHOW_MAP_BODY(Text14)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Normal9,126,120,185,149)

SHOW_MAP_BEGIN(UIFlowWndProcessing_StaticText_Progress)
SHOW_MAP_BODY(Normal9)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndProcessing_StaticText_Progress)
CREATE_STATIC_DATA(UIFlowWndProcessing_StaticText_Progress,STRID_MODE)
CREATE_STATIC_CTRL(UIFlowWndProcessing_StaticText_Progress,0,126,120,185,149)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_MAP_BEGIN(UIFlowWndProcessing)
SHOW_MAP_BODY(Skin1)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndProcessing)
DECLARE_CTRL_LIST(UIFlowWndProcessing)
CREATE_CTRL(UIFlowWndProcessing,UIFlowWndProcessing,CTRL_WND,NULL,0 ,0,0,319,239)
#endif
