//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndPlayDelRes.c"
#include "UIMenuWndPlayDel.h"
#include "PrjCfg.h"

//---------------------UIMenuWndPlayDelCtrl Debug Definition -----------------------------
#define _UIMENUWNDPLAYDEL_ERROR_MSG        1
#define _UIMENUWNDPLAYDEL_TRACE_MSG        0

#if (_UIMENUWNDPLAYDEL_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndPlayDelErrMsg(...)            debug_msg ("^R UIMenuWndPlayDel: "__VA_ARGS__)
#else
#define UIMenuWndPlayDelErrMsg(...)
#endif

#if (_UIMENUWNDPLAYDEL_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndPlayDelTraceMsg(...)          debug_msg ("^B UIMenuWndPlayDel: "__VA_ARGS__)
#else
#define UIMenuWndPlayDelTraceMsg(...)
#endif

//---------------------UIMenuWndPlayDelCtrl Global Variables -----------------------------

//---------------------UIMenuWndPlayDelCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndPlayDelCtrl Public API  ----------------------------------

//---------------------UIMenuWndPlayDelCtrl Private API  ---------------------------------
//---------------------UIMenuWndPlayDelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPlayDel)
CTRL_LIST_ITEM(UIMenuWndPlayDel_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPlayDelCtrl Event---------------------------
INT32 UIMenuWndPlayDel_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayDel_OnClose(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPlayDel)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndPlayDel_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndPlayDel_OnClose)
EVENT_END

INT32 UIMenuWndPlayDel_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayDel_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
//---------------------UIMenuWndPlayDel_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPlayDel_Panel)
CTRL_LIST_ITEM(UIMenuWndPlayDel_Menu)
CTRL_LIST_END

//----------------------UIMenuWndPlayDel_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPlayDel_Panel)
EVENT_END

//----------------------UIMenuWndPlayDel_MenuCtrl Event---------------------------
INT32 UIMenuWndPlayDel_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayDel_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayDel_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPlayDel_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndPlayDel_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndPlayDel_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndPlayDel_Menu_OnKeyEnter)
EVENT_END

INT32 UIMenuWndPlayDel_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayDel_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayDel_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
