//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "MenuCommonItemRes.c"
#include "MenuCommonItem.h"
#include "PrjCfg.h"

//---------------------MenuCommonItemCtrl Debug Definition -----------------------------
#define _MENUCOMMONITEM_ERROR_MSG        1
#define _MENUCOMMONITEM_TRACE_MSG        0

#if (_MENUCOMMONITEM_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define MenuCommonItemErrMsg(...)            debug_msg ("^R MenuCommonItem: "__VA_ARGS__)
#else
#define MenuCommonItemErrMsg(...)
#endif

#if (_MENUCOMMONITEM_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define MenuCommonItemTraceMsg(...)          debug_msg ("^B MenuCommonItem: "__VA_ARGS__)
#else
#define MenuCommonItemTraceMsg(...)
#endif

//---------------------MenuCommonItemCtrl Global Variables -----------------------------

//---------------------MenuCommonItemCtrl Prototype Declaration  -----------------------

//---------------------MenuCommonItemCtrl Public API  ----------------------------------

//---------------------MenuCommonItemCtrl Private API  ---------------------------------
//---------------------MenuCommonItemCtrl Control List---------------------------
CTRL_LIST_BEGIN(MenuCommonItem)
CTRL_LIST_ITEM(MenuCommonItem_BG)
CTRL_LIST_ITEM(MenuCommonItem_TitleBar)
CTRL_LIST_ITEM(MenuCommonItem_TipsBar)
CTRL_LIST_ITEM(MenuCommonItem_Menu)
CTRL_LIST_END

//----------------------MenuCommonItemCtrl Event---------------------------
INT32 MenuCommonItem_OnOpen(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_OnClose(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(MenuCommonItem)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,MenuCommonItem_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,MenuCommonItem_OnClose)
EVENT_END

INT32 MenuCommonItem_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 MenuCommonItem_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
//---------------------MenuCommonItem_BGCtrl Control List---------------------------
CTRL_LIST_BEGIN(MenuCommonItem_BG)
CTRL_LIST_END

//----------------------MenuCommonItem_BGCtrl Event---------------------------
EVENT_BEGIN(MenuCommonItem_BG)
EVENT_END

//---------------------MenuCommonItem_TitleBarCtrl Control List---------------------------
CTRL_LIST_BEGIN(MenuCommonItem_TitleBar)
CTRL_LIST_ITEM(MenuCommonItem_TitleIconTab1)
CTRL_LIST_ITEM(MenuCommonItem_TitleIconTab2)
CTRL_LIST_ITEM(MenuCommonItem_TitleText)
CTRL_LIST_END

//----------------------MenuCommonItem_TitleBarCtrl Event---------------------------
EVENT_BEGIN(MenuCommonItem_TitleBar)
EVENT_END

//----------------------MenuCommonItem_TitleIconTab1Ctrl Event---------------------------
EVENT_BEGIN(MenuCommonItem_TitleIconTab1)
EVENT_END

//----------------------MenuCommonItem_TitleIconTab2Ctrl Event---------------------------
EVENT_BEGIN(MenuCommonItem_TitleIconTab2)
EVENT_END

//----------------------MenuCommonItem_TitleTextCtrl Event---------------------------
EVENT_BEGIN(MenuCommonItem_TitleText)
EVENT_END

//---------------------MenuCommonItem_TipsBarCtrl Control List---------------------------
CTRL_LIST_BEGIN(MenuCommonItem_TipsBar)
CTRL_LIST_ITEM(MenuCommonItem_TipsIconReturn)
CTRL_LIST_ITEM(MenuCommonItem_TipsIconLDR)
CTRL_LIST_ITEM(MenuCommonItem_TipsIconLUDR)
CTRL_LIST_ITEM(MenuCommonItem_TipsIconLUDOK)
CTRL_LIST_ITEM(MenuCommonItem_PageNum)
CTRL_LIST_END

//----------------------MenuCommonItem_TipsBarCtrl Event---------------------------
EVENT_BEGIN(MenuCommonItem_TipsBar)
EVENT_END

//----------------------MenuCommonItem_TipsIconReturnCtrl Event---------------------------
EVENT_BEGIN(MenuCommonItem_TipsIconReturn)
EVENT_END

//---------------------MenuCommonItem_TipsIconLDRCtrl Control List---------------------------
CTRL_LIST_BEGIN(MenuCommonItem_TipsIconLDR)
CTRL_LIST_END

//----------------------MenuCommonItem_TipsIconLDRCtrl Event---------------------------
EVENT_BEGIN(MenuCommonItem_TipsIconLDR)
EVENT_END

//---------------------MenuCommonItem_TipsIconLUDRCtrl Control List---------------------------
CTRL_LIST_BEGIN(MenuCommonItem_TipsIconLUDR)
CTRL_LIST_END

//----------------------MenuCommonItem_TipsIconLUDRCtrl Event---------------------------
EVENT_BEGIN(MenuCommonItem_TipsIconLUDR)
EVENT_END

//---------------------MenuCommonItem_TipsIconLUDOKCtrl Control List---------------------------
CTRL_LIST_BEGIN(MenuCommonItem_TipsIconLUDOK)
CTRL_LIST_END

//----------------------MenuCommonItem_TipsIconLUDOKCtrl Event---------------------------
EVENT_BEGIN(MenuCommonItem_TipsIconLUDOK)
EVENT_END

//----------------------MenuCommonItem_PageNumCtrl Event---------------------------
EVENT_BEGIN(MenuCommonItem_PageNum)
EVENT_END

//----------------------MenuCommonItem_MenuCtrl Event---------------------------
INT32 MenuCommonItem_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_Menu_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_Menu_OnKeyRight(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(MenuCommonItem_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,MenuCommonItem_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,MenuCommonItem_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_LEFT,MenuCommonItem_Menu_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_RIGHT,MenuCommonItem_Menu_OnKeyRight)
EVENT_END

INT32 MenuCommonItem_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 MenuCommonItem_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 MenuCommonItem_Menu_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 MenuCommonItem_Menu_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
