//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndUSBRes.c"
#include "UIMenuWndUSB.h"
#include "PrjCfg.h"

//---------------------UIMenuWndUSBCtrl Debug Definition -----------------------------
#define _UIMENUWNDUSB_ERROR_MSG        1
#define _UIMENUWNDUSB_TRACE_MSG        0

#if (_UIMENUWNDUSB_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndUSBErrMsg(...)            debug_msg ("^R UIMenuWndUSB: "__VA_ARGS__)
#else
#define UIMenuWndUSBErrMsg(...)
#endif

#if (_UIMENUWNDUSB_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndUSBTraceMsg(...)          debug_msg ("^B UIMenuWndUSB: "__VA_ARGS__)
#else
#define UIMenuWndUSBTraceMsg(...)
#endif

//---------------------UIMenuWndUSBCtrl Global Variables -----------------------------

//---------------------UIMenuWndUSBCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndUSBCtrl Public API  ----------------------------------

//---------------------UIMenuWndUSBCtrl Private API  ---------------------------------
//---------------------UIMenuWndUSBCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndUSB)
CTRL_LIST_ITEM(UIMenuWndUSB_Background)
CTRL_LIST_ITEM(UIMenuWndUSB_TitleBar)
CTRL_LIST_ITEM(UIMenuWndUSB_TipsBar)
CTRL_LIST_ITEM(UIMenuWndUSB_Item)
CTRL_LIST_END

//----------------------UIMenuWndUSBCtrl Event---------------------------
INT32 UIMenuWndUSB_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndUSB_OnClose(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndUSB)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndUSB_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndUSB_OnClose)
EVENT_END

INT32 UIMenuWndUSB_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndUSB_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
//---------------------UIMenuWndUSB_BackgroundCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndUSB_Background)
CTRL_LIST_END

//----------------------UIMenuWndUSB_BackgroundCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndUSB_Background)
EVENT_END

//---------------------UIMenuWndUSB_TitleBarCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndUSB_TitleBar)
CTRL_LIST_ITEM(UIMenuWndUSB_TitleName)
CTRL_LIST_END

//----------------------UIMenuWndUSB_TitleBarCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndUSB_TitleBar)
EVENT_END

//----------------------UIMenuWndUSB_TitleNameCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndUSB_TitleName)
EVENT_END

//---------------------UIMenuWndUSB_TipsBarCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndUSB_TipsBar)
CTRL_LIST_ITEM(UIMenuWndUSB_UDOKTips)
CTRL_LIST_END

//----------------------UIMenuWndUSB_TipsBarCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndUSB_TipsBar)
EVENT_END

//---------------------UIMenuWndUSB_UDOKTipsCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndUSB_UDOKTips)
CTRL_LIST_END

//----------------------UIMenuWndUSB_UDOKTipsCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndUSB_UDOKTips)
EVENT_END

//----------------------UIMenuWndUSB_ItemCtrl Event---------------------------
INT32 UIMenuWndUSB_Item_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndUSB_Item_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndUSB_Item_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndUSB_Item)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndUSB_Item_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndUSB_Item_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndUSB_Item_OnKeyEnter)
EVENT_END

INT32 UIMenuWndUSB_Item_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndUSB_Item_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndUSB_Item_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
